export const CRAWL_PAGE_STATUS = {
  PENDING: "PENDING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  BLOCKED: "BLOCKED",
  REQUIRES_LOGIN: "REQUIRES_LOGIN",
  CAPTCHA_DETECTED: "CAPTCHA_DETECTED",
  PAYWALL_DETECTED: "PAYWALL_DETECTED",
  TIMEOUT: "TIMEOUT",
  SKIPPED: "SKIPPED",
} as const;

export type CrawlPageStatus = keyof typeof CRAWL_PAGE_STATUS;
