export const JOB_STATUS = {
  PENDING: "PENDING",
  QUEUED: "QUEUED",
  RUNNING: "RUNNING",
  PROCESSING_EXPORT: "PROCESSING_EXPORT",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  CANCELED: "CANCELED",
  EXPIRED: "EXPIRED",
} as const;

export type JobStatus = keyof typeof JOB_STATUS;
